# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(369, 477)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(369, 477))
        MainWindow.setMaximumSize(QtCore.QSize(369, 477))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rem = QtWidgets.QPushButton(self.centralwidget)
        self.rem.setGeometry(QtCore.QRect(190, 370, 150, 80))
        self.rem.setObjectName("rem")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(190, 290, 150, 75))
        self.add.setObjectName("add")
        self.best = QtWidgets.QPushButton(self.centralwidget)
        self.best.setGeometry(QtCore.QRect(20, 290, 150, 161))
        self.best.setObjectName("best")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(30, 160, 311, 51))
        self.name.setText("")
        self.name.setObjectName("name")
        self.ball = QtWidgets.QLineEdit(self.centralwidget)
        self.ball.setGeometry(QtCore.QRect(190, 220, 151, 61))
        self.ball.setText("")
        self.ball.setObjectName("ball")
        self.txt = QtWidgets.QLabel(self.centralwidget)
        self.txt.setGeometry(QtCore.QRect(20, 220, 331, 41))
        self.txt.setObjectName("txt")
        self.txt2 = QtWidgets.QLabel(self.centralwidget)
        self.txt2.setGeometry(QtCore.QRect(20, 260, 171, 16))
        self.txt2.setObjectName("txt2")
        self.ann = QtWidgets.QTextBrowser(self.centralwidget)
        self.ann.setGeometry(QtCore.QRect(30, 40, 311, 51))
        self.ann.setObjectName("textBrowser")
        self.best_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.best_2.setGeometry(QtCore.QRect(30, 100, 311, 51))
        self.best_2.setObjectName("textBrowser_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "БД"))
        self.rem.setText(_translate("MainWindow", "Удалить тяночку"))
        self.add.setText(_translate("MainWindow", "Добавить тяночку"))
        self.best.setText(_translate("MainWindow", "Лучшая аниме девочка"))
        self.txt.setText(_translate("MainWindow", "На сколько по стобальной"))
        self.txt2.setText(_translate("MainWindow", "шкале вы ее оцениваете:"))
